// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestBankProject
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// First test
        /// </summary>
        public void TestGUI()
        {
            #region Variable Declarations
            WinEdit uITxtTaiKhoanEdit = this.UIFrmDangNhapWindow.UITxtTaiKhoanWindow.UITxtTaiKhoanEdit;
            WinEdit uITxtMatKhauEdit = this.UIFrmDangNhapWindow.UITxtMatKhauWindow.UITxtMatKhauEdit;
            WinWindow uILoginWindow = this.UIFrmDangNhapWindow.UITableLayoutPanel1Window.UILoginWindow;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            WinWindow uITxtTaiKhoanWindow = this.UIFrmDangNhapWindow.UITableLayoutPanel1Window.UITxtTaiKhoanWindow;
            WinWindow uITxtSoTienWindow = this.UIFrmChucNangWindow.UIFrmChucNangClient.UITxtSoTienWindow;
            WinEdit uITxtSoTienEdit = this.UIFrmChucNangWindow.UITxtSoTienWindow.UITxtSoTienEdit;
            WinWindow uIBtnCreditWindow = this.UIFrmChucNangWindow.UIFrmChucNangClient.UIBtnCreditWindow;
            WinWindow uIBtnDebitWindow = this.UIFrmChucNangWindow.UIFrmChucNangClient.UIBtnDebitWindow;
            WinWindow uILogoutWindow = this.UIFrmChucNangWindow.UIFrmChucNangClient.UILogoutWindow;
            WinEdit uITxtTaiKhoanEdit1 = this.UIFrmDangNhapWindow1.UITxtTaiKhoanWindow.UITxtTaiKhoanEdit;
            WinEdit uITxtMatKhauEdit1 = this.UIFrmDangNhapWindow1.UITxtMatKhauWindow.UITxtMatKhauEdit;
            WinWindow uILoginWindow1 = this.UIFrmDangNhapWindow1.UITableLayoutPanel1Window.UILoginWindow;
            WinWindow uITxtSoTienWindow1 = this.UIFrmChucNangWindow1.UIFrmChucNangClient.UITxtSoTienWindow;
            WinEdit uITxtSoTienEdit1 = this.UIFrmChucNangWindow1.UITxtSoTienWindow.UITxtSoTienEdit;
            WinButton uIBtnCreditButton = this.UIFrmChucNangWindow1.UIBtnCreditWindow.UIBtnCreditButton;
            WinButton uIBtnDebitButton = this.UIFrmChucNangWindow1.UIBtnDebitWindow.UIBtnDebitButton;
            WinWindow uILogoutWindow1 = this.UIFrmChucNangWindow1.UIFrmChucNangClient.UILogoutWindow;
            WinWindow uIFrmDangNhapWindow2 = this.UIFrmDangNhapWindow2;
            #endregion

            // Launch '%USERPROFILE%\Desktop\UnitTestExample\BankProject\bin\Debug\BankProject.exe'
            ApplicationUnderTest uIFrmDangNhapWindow = ApplicationUnderTest.Launch(this.TestGUIParams.UIFrmDangNhapWindowExePath, this.TestGUIParams.UIFrmDangNhapWindowAlternateExePath);

            // Type 'tri' in 'txtTaiKhoan' text box
            uITxtTaiKhoanEdit.Text = this.TestGUIParams.UITxtTaiKhoanEditText;

            // Type '{Tab}' in 'txtTaiKhoan' text box
            Keyboard.SendKeys(uITxtTaiKhoanEdit, this.TestGUIParams.UITxtTaiKhoanEditSendKeys, ModifierKeys.None);

            // Type '********' in 'txtMatKhau' text box
            Keyboard.SendKeys(uITxtMatKhauEdit, this.TestGUIParams.UITxtMatKhauEditSendKeys, true);

            // Click 'Login' window
            Mouse.Click(uILoginWindow, new Point(106, 72));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(84, 19));

            // Click 'txtTaiKhoan' window
            Mouse.Click(uITxtTaiKhoanWindow, new Point(134, 65));

            // Type 'triem' in 'txtTaiKhoan' text box
            uITxtTaiKhoanEdit.Text = this.TestGUIParams.UITxtTaiKhoanEditText1;

            // Click 'Login' window
            Mouse.Click(uILoginWindow, new Point(139, 73));

            // Click 'txtSoTien' window
            Mouse.Click(uITxtSoTienWindow, new Point(105, 66));

            // Type '100' in 'txtSoTien' text box
            uITxtSoTienEdit.Text = this.TestGUIParams.UITxtSoTienEditText;

            // Click 'btnCredit' window
            Mouse.Click(uIBtnCreditWindow, new Point(199, 168));

            // Click 'txtSoTien' window
            Mouse.Click(uITxtSoTienWindow, new Point(148, 64));

            // Type '20' in 'txtSoTien' text box
            uITxtSoTienEdit.Text = this.TestGUIParams.UITxtSoTienEditText1;

            // Click 'btnDebit' window
            Mouse.Click(uIBtnDebitWindow, new Point(184, 174));

            // Click 'Logout' window
            Mouse.Click(uILogoutWindow, new Point(114, 141));

            // Type 'locus' in 'txtTaiKhoan' text box
            uITxtTaiKhoanEdit1.Text = this.TestGUIParams.UITxtTaiKhoanEditText2;

            // Type '{Tab}' in 'txtTaiKhoan' text box
            Keyboard.SendKeys(uITxtTaiKhoanEdit1, this.TestGUIParams.UITxtTaiKhoanEditSendKeys1, ModifierKeys.None);

            // Type '********' in 'txtMatKhau' text box
            Keyboard.SendKeys(uITxtMatKhauEdit1, this.TestGUIParams.UITxtMatKhauEditSendKeys1, true);

            // Click 'Login' window
            Mouse.Click(uILoginWindow1, new Point(117, 83));

            // Click 'txtSoTien' window
            Mouse.Click(uITxtSoTienWindow1, new Point(113, 38));

            // Click 'txtSoTien' window
            Mouse.Click(uITxtSoTienWindow1, new Point(113, 27));

            // Type '100' in 'txtSoTien' text box
            uITxtSoTienEdit1.Text = this.TestGUIParams.UITxtSoTienEditText2;

            // Click 'btnCredit' button
            Mouse.Click(uIBtnCreditButton, new Point(132, 153));

            // Click 'txtSoTien' window
            Mouse.Click(uITxtSoTienWindow1, new Point(118, 25));

            // Type '33' in 'txtSoTien' text box
            uITxtSoTienEdit1.Text = this.TestGUIParams.UITxtSoTienEditText3;

            // Click 'btnDebit' button
            Mouse.Click(uIBtnDebitButton, new Point(115, 151));

            // Click 'Logout' window
            Mouse.Click(uILogoutWindow1, new Point(40, 108));

            // Click 'FrmDangNhap' window
            Mouse.Click(uIFrmDangNhapWindow2, new Point(426, 28));
        }
        
        /// <summary>
        /// TestGUIFrmDangNhap - Use 'TestGUIFrmDangNhapParams' to pass parameters into this method.
        /// </summary>
        public void TestGUIFrmDangNhap()
        {
            #region Variable Declarations
            WinEdit uITxtTaiKhoanEdit = this.UIFrmDangNhapWindow.UITxtTaiKhoanWindow.UITxtTaiKhoanEdit;
            WinEdit uITxtMatKhauEdit = this.UIFrmDangNhapWindow.UITxtMatKhauWindow.UITxtMatKhauEdit;
            #endregion

            // Launch '%USERPROFILE%\Desktop\UnitTestExample\BankProject\bin\Debug\BankProject.exe'
            ApplicationUnderTest uIFrmDangNhapWindow = ApplicationUnderTest.Launch(this.TestGUIFrmDangNhapParams.UIFrmDangNhapWindowExePath, this.TestGUIFrmDangNhapParams.UIFrmDangNhapWindowAlternateExePath);

            // Type 'triem' in 'txtTaiKhoan' text box
            uITxtTaiKhoanEdit.Text = this.TestGUIFrmDangNhapParams.UITxtTaiKhoanEditText;

            // Type '{Tab}' in 'txtTaiKhoan' text box
            Keyboard.SendKeys(uITxtTaiKhoanEdit, this.TestGUIFrmDangNhapParams.UITxtTaiKhoanEditSendKeys, ModifierKeys.None);

            // Type '********' in 'txtMatKhau' text box
            Keyboard.SendKeys(uITxtMatKhauEdit, this.TestGUIFrmDangNhapParams.UITxtMatKhauEditSendKeys, true);
        }
        
        /// <summary>
        /// CheckUsername - Use 'CheckUsernameExpectedValues' to pass parameters into this method.
        /// </summary>
        public void CheckUsername()
        {
            #region Variable Declarations
            WinEdit uITxtTaiKhoanEdit = this.UIFrmDangNhapWindow.UITxtTaiKhoanWindow.UITxtTaiKhoanEdit;
            #endregion

            // Verify that the 'Text' property of 'txtTaiKhoan' text box equals 'triem'
            Assert.AreEqual(this.CheckUsernameExpectedValues.UITxtTaiKhoanEditControlType, uITxtTaiKhoanEdit.ControlType.ToString(), "Wrong username");
        }
        
        #region Properties
        public virtual TestGUIParams TestGUIParams
        {
            get
            {
                if ((this.mTestGUIParams == null))
                {
                    this.mTestGUIParams = new TestGUIParams();
                }
                return this.mTestGUIParams;
            }
        }
        
        public virtual TestGUIFrmDangNhapParams TestGUIFrmDangNhapParams
        {
            get
            {
                if ((this.mTestGUIFrmDangNhapParams == null))
                {
                    this.mTestGUIFrmDangNhapParams = new TestGUIFrmDangNhapParams();
                }
                return this.mTestGUIFrmDangNhapParams;
            }
        }
        
        public virtual CheckUsernameExpectedValues CheckUsernameExpectedValues
        {
            get
            {
                if ((this.mCheckUsernameExpectedValues == null))
                {
                    this.mCheckUsernameExpectedValues = new CheckUsernameExpectedValues();
                }
                return this.mCheckUsernameExpectedValues;
            }
        }
        
        public UIFrmDangNhapWindow UIFrmDangNhapWindow
        {
            get
            {
                if ((this.mUIFrmDangNhapWindow == null))
                {
                    this.mUIFrmDangNhapWindow = new UIFrmDangNhapWindow();
                }
                return this.mUIFrmDangNhapWindow;
            }
        }
        
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow();
                }
                return this.mUIOKWindow;
            }
        }
        
        public UIFrmChucNangWindow UIFrmChucNangWindow
        {
            get
            {
                if ((this.mUIFrmChucNangWindow == null))
                {
                    this.mUIFrmChucNangWindow = new UIFrmChucNangWindow();
                }
                return this.mUIFrmChucNangWindow;
            }
        }
        
        public UIFrmDangNhapWindow1 UIFrmDangNhapWindow1
        {
            get
            {
                if ((this.mUIFrmDangNhapWindow1 == null))
                {
                    this.mUIFrmDangNhapWindow1 = new UIFrmDangNhapWindow1();
                }
                return this.mUIFrmDangNhapWindow1;
            }
        }
        
        public UIFrmChucNangWindow1 UIFrmChucNangWindow1
        {
            get
            {
                if ((this.mUIFrmChucNangWindow1 == null))
                {
                    this.mUIFrmChucNangWindow1 = new UIFrmChucNangWindow1();
                }
                return this.mUIFrmChucNangWindow1;
            }
        }
        
        public UIFrmDangNhapWindow2 UIFrmDangNhapWindow2
        {
            get
            {
                if ((this.mUIFrmDangNhapWindow2 == null))
                {
                    this.mUIFrmDangNhapWindow2 = new UIFrmDangNhapWindow2();
                }
                return this.mUIFrmDangNhapWindow2;
            }
        }
        #endregion
        
        #region Fields
        private TestGUIParams mTestGUIParams;
        
        private TestGUIFrmDangNhapParams mTestGUIFrmDangNhapParams;
        
        private CheckUsernameExpectedValues mCheckUsernameExpectedValues;
        
        private UIFrmDangNhapWindow mUIFrmDangNhapWindow;
        
        private UIOKWindow mUIOKWindow;
        
        private UIFrmChucNangWindow mUIFrmChucNangWindow;
        
        private UIFrmDangNhapWindow1 mUIFrmDangNhapWindow1;
        
        private UIFrmChucNangWindow1 mUIFrmChucNangWindow1;
        
        private UIFrmDangNhapWindow2 mUIFrmDangNhapWindow2;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestGUI'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class TestGUIParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%USERPROFILE%\Desktop\UnitTestExample\BankProject\bin\Debug\BankProject.exe'
        /// </summary>
        public string UIFrmDangNhapWindowExePath = "C:\\Users\\hodan\\Desktop\\UnitTestExample\\BankProject\\bin\\Debug\\BankProject.exe";
        
        /// <summary>
        /// Launch '%USERPROFILE%\Desktop\UnitTestExample\BankProject\bin\Debug\BankProject.exe'
        /// </summary>
        public string UIFrmDangNhapWindowAlternateExePath = "%USERPROFILE%\\Desktop\\UnitTestExample\\BankProject\\bin\\Debug\\BankProject.exe";
        
        /// <summary>
        /// Type 'tri' in 'txtTaiKhoan' text box
        /// </summary>
        public string UITxtTaiKhoanEditText = "tri";
        
        /// <summary>
        /// Type '{Tab}' in 'txtTaiKhoan' text box
        /// </summary>
        public string UITxtTaiKhoanEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'txtMatKhau' text box
        /// </summary>
        public string UITxtMatKhauEditSendKeys = "mOL/lXDUSd/hy7K5BZnJEA==";
        
        /// <summary>
        /// Type 'triem' in 'txtTaiKhoan' text box
        /// </summary>
        public string UITxtTaiKhoanEditText1 = "triem";
        
        /// <summary>
        /// Type '100' in 'txtSoTien' text box
        /// </summary>
        public string UITxtSoTienEditText = "100";
        
        /// <summary>
        /// Type '20' in 'txtSoTien' text box
        /// </summary>
        public string UITxtSoTienEditText1 = "20";
        
        /// <summary>
        /// Type 'locus' in 'txtTaiKhoan' text box
        /// </summary>
        public string UITxtTaiKhoanEditText2 = "locus";
        
        /// <summary>
        /// Type '{Tab}' in 'txtTaiKhoan' text box
        /// </summary>
        public string UITxtTaiKhoanEditSendKeys1 = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'txtMatKhau' text box
        /// </summary>
        public string UITxtMatKhauEditSendKeys1 = "oIb8ijgM0PATqaIE8zzf5g==";
        
        /// <summary>
        /// Type '100' in 'txtSoTien' text box
        /// </summary>
        public string UITxtSoTienEditText2 = "100";
        
        /// <summary>
        /// Type '33' in 'txtSoTien' text box
        /// </summary>
        public string UITxtSoTienEditText3 = "33";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestGUIFrmDangNhap'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class TestGUIFrmDangNhapParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%USERPROFILE%\Desktop\UnitTestExample\BankProject\bin\Debug\BankProject.exe'
        /// </summary>
        public string UIFrmDangNhapWindowExePath = "C:\\Users\\hodan\\Desktop\\UnitTestExample\\BankProject\\bin\\Debug\\BankProject.exe";
        
        /// <summary>
        /// Launch '%USERPROFILE%\Desktop\UnitTestExample\BankProject\bin\Debug\BankProject.exe'
        /// </summary>
        public string UIFrmDangNhapWindowAlternateExePath = "%USERPROFILE%\\Desktop\\UnitTestExample\\BankProject\\bin\\Debug\\BankProject.exe";
        
        /// <summary>
        /// Type 'triem' in 'txtTaiKhoan' text box
        /// </summary>
        public string UITxtTaiKhoanEditText = "triem";
        
        /// <summary>
        /// Type '{Tab}' in 'txtTaiKhoan' text box
        /// </summary>
        public string UITxtTaiKhoanEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'txtMatKhau' text box
        /// </summary>
        public string UITxtMatKhauEditSendKeys = "mOL/lXDUSd/hy7K5BZnJEA==";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'CheckUsername'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class CheckUsernameExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'ControlType' property of 'txtTaiKhoan' text box equals 'triem'
        /// </summary>
        public string UITxtTaiKhoanEditControlType = "triem";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIFrmDangNhapWindow : WinWindow
    {
        
        public UIFrmDangNhapWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "FrmDangNhap";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("FrmDangNhap");
            #endregion
        }
        
        #region Properties
        public UITxtTaiKhoanWindow UITxtTaiKhoanWindow
        {
            get
            {
                if ((this.mUITxtTaiKhoanWindow == null))
                {
                    this.mUITxtTaiKhoanWindow = new UITxtTaiKhoanWindow(this);
                }
                return this.mUITxtTaiKhoanWindow;
            }
        }
        
        public UITxtMatKhauWindow UITxtMatKhauWindow
        {
            get
            {
                if ((this.mUITxtMatKhauWindow == null))
                {
                    this.mUITxtMatKhauWindow = new UITxtMatKhauWindow(this);
                }
                return this.mUITxtMatKhauWindow;
            }
        }
        
        public UITableLayoutPanel1Window UITableLayoutPanel1Window
        {
            get
            {
                if ((this.mUITableLayoutPanel1Window == null))
                {
                    this.mUITableLayoutPanel1Window = new UITableLayoutPanel1Window(this);
                }
                return this.mUITableLayoutPanel1Window;
            }
        }
        #endregion
        
        #region Fields
        private UITxtTaiKhoanWindow mUITxtTaiKhoanWindow;
        
        private UITxtMatKhauWindow mUITxtMatKhauWindow;
        
        private UITableLayoutPanel1Window mUITableLayoutPanel1Window;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITxtTaiKhoanWindow : WinWindow
    {
        
        public UITxtTaiKhoanWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtTaiKhoan";
            this.WindowTitles.Add("FrmDangNhap");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtTaiKhoanEdit
        {
            get
            {
                if ((this.mUITxtTaiKhoanEdit == null))
                {
                    this.mUITxtTaiKhoanEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtTaiKhoanEdit.WindowTitles.Add("FrmDangNhap");
                    #endregion
                }
                return this.mUITxtTaiKhoanEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtTaiKhoanEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITxtMatKhauWindow : WinWindow
    {
        
        public UITxtMatKhauWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtMatKhau";
            this.WindowTitles.Add("FrmDangNhap");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtMatKhauEdit
        {
            get
            {
                if ((this.mUITxtMatKhauEdit == null))
                {
                    this.mUITxtMatKhauEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtMatKhauEdit.WindowTitles.Add("FrmDangNhap");
                    #endregion
                }
                return this.mUITxtMatKhauEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtMatKhauEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITableLayoutPanel1Window : WinWindow
    {
        
        public UITableLayoutPanel1Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "tableLayoutPanel1";
            this.WindowTitles.Add("FrmDangNhap");
            #endregion
        }
        
        #region Properties
        public WinWindow UILoginWindow
        {
            get
            {
                if ((this.mUILoginWindow == null))
                {
                    this.mUILoginWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUILoginWindow.SearchProperties[WinWindow.PropertyNames.Name] = "Login";
                    this.mUILoginWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains));
                    this.mUILoginWindow.WindowTitles.Add("FrmDangNhap");
                    #endregion
                }
                return this.mUILoginWindow;
            }
        }
        
        public WinWindow UITxtTaiKhoanWindow
        {
            get
            {
                if ((this.mUITxtTaiKhoanWindow == null))
                {
                    this.mUITxtTaiKhoanWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUITxtTaiKhoanWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITxtTaiKhoanWindow.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
                    this.mUITxtTaiKhoanWindow.WindowTitles.Add("FrmDangNhap");
                    #endregion
                }
                return this.mUITxtTaiKhoanWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUILoginWindow;
        
        private WinWindow mUITxtTaiKhoanWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "OK";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Button";
            this.WindowTitles.Add("OK");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("OK");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIFrmChucNangWindow : WinWindow
    {
        
        public UIFrmChucNangWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "FrmChucNang";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("FrmChucNang");
            #endregion
        }
        
        #region Properties
        public UIFrmChucNangClient UIFrmChucNangClient
        {
            get
            {
                if ((this.mUIFrmChucNangClient == null))
                {
                    this.mUIFrmChucNangClient = new UIFrmChucNangClient(this);
                }
                return this.mUIFrmChucNangClient;
            }
        }
        
        public UITxtSoTienWindow UITxtSoTienWindow
        {
            get
            {
                if ((this.mUITxtSoTienWindow == null))
                {
                    this.mUITxtSoTienWindow = new UITxtSoTienWindow(this);
                }
                return this.mUITxtSoTienWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIFrmChucNangClient mUIFrmChucNangClient;
        
        private UITxtSoTienWindow mUITxtSoTienWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIFrmChucNangClient : WinClient
    {
        
        public UIFrmChucNangClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "FrmChucNang";
            this.WindowTitles.Add("FrmChucNang");
            #endregion
        }
        
        #region Properties
        public WinWindow UITxtSoTienWindow
        {
            get
            {
                if ((this.mUITxtSoTienWindow == null))
                {
                    this.mUITxtSoTienWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUITxtSoTienWindow.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Số tiền:";
                    this.mUITxtSoTienWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITxtSoTienWindow.WindowTitles.Add("FrmChucNang");
                    #endregion
                }
                return this.mUITxtSoTienWindow;
            }
        }
        
        public WinWindow UIBtnCreditWindow
        {
            get
            {
                if ((this.mUIBtnCreditWindow == null))
                {
                    this.mUIBtnCreditWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIBtnCreditWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains));
                    this.mUIBtnCreditWindow.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
                    this.mUIBtnCreditWindow.WindowTitles.Add("FrmChucNang");
                    #endregion
                }
                return this.mUIBtnCreditWindow;
            }
        }
        
        public WinWindow UIBtnDebitWindow
        {
            get
            {
                if ((this.mUIBtnDebitWindow == null))
                {
                    this.mUIBtnDebitWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIBtnDebitWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains));
                    this.mUIBtnDebitWindow.WindowTitles.Add("FrmChucNang");
                    #endregion
                }
                return this.mUIBtnDebitWindow;
            }
        }
        
        public WinWindow UILogoutWindow
        {
            get
            {
                if ((this.mUILogoutWindow == null))
                {
                    this.mUILogoutWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUILogoutWindow.SearchProperties[WinWindow.PropertyNames.Name] = "Logout";
                    this.mUILogoutWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains));
                    this.mUILogoutWindow.WindowTitles.Add("FrmChucNang");
                    #endregion
                }
                return this.mUILogoutWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUITxtSoTienWindow;
        
        private WinWindow mUIBtnCreditWindow;
        
        private WinWindow mUIBtnDebitWindow;
        
        private WinWindow mUILogoutWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITxtSoTienWindow : WinWindow
    {
        
        public UITxtSoTienWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtSoTien";
            this.WindowTitles.Add("FrmChucNang");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtSoTienEdit
        {
            get
            {
                if ((this.mUITxtSoTienEdit == null))
                {
                    this.mUITxtSoTienEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtSoTienEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Số tiền:";
                    this.mUITxtSoTienEdit.WindowTitles.Add("FrmChucNang");
                    #endregion
                }
                return this.mUITxtSoTienEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtSoTienEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIFrmDangNhapWindow1 : WinWindow
    {
        
        public UIFrmDangNhapWindow1()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "FrmDangNhap";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.FilterProperties[WinWindow.PropertyNames.OrderOfInvocation] = "2";
            this.WindowTitles.Add("FrmDangNhap");
            #endregion
        }
        
        #region Properties
        public UITxtTaiKhoanWindow1 UITxtTaiKhoanWindow
        {
            get
            {
                if ((this.mUITxtTaiKhoanWindow == null))
                {
                    this.mUITxtTaiKhoanWindow = new UITxtTaiKhoanWindow1(this);
                }
                return this.mUITxtTaiKhoanWindow;
            }
        }
        
        public UITxtMatKhauWindow1 UITxtMatKhauWindow
        {
            get
            {
                if ((this.mUITxtMatKhauWindow == null))
                {
                    this.mUITxtMatKhauWindow = new UITxtMatKhauWindow1(this);
                }
                return this.mUITxtMatKhauWindow;
            }
        }
        
        public UITableLayoutPanel1Window1 UITableLayoutPanel1Window
        {
            get
            {
                if ((this.mUITableLayoutPanel1Window == null))
                {
                    this.mUITableLayoutPanel1Window = new UITableLayoutPanel1Window1(this);
                }
                return this.mUITableLayoutPanel1Window;
            }
        }
        #endregion
        
        #region Fields
        private UITxtTaiKhoanWindow1 mUITxtTaiKhoanWindow;
        
        private UITxtMatKhauWindow1 mUITxtMatKhauWindow;
        
        private UITableLayoutPanel1Window1 mUITableLayoutPanel1Window;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITxtTaiKhoanWindow1 : WinWindow
    {
        
        public UITxtTaiKhoanWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtTaiKhoan";
            this.WindowTitles.Add("FrmDangNhap");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtTaiKhoanEdit
        {
            get
            {
                if ((this.mUITxtTaiKhoanEdit == null))
                {
                    this.mUITxtTaiKhoanEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtTaiKhoanEdit.WindowTitles.Add("FrmDangNhap");
                    #endregion
                }
                return this.mUITxtTaiKhoanEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtTaiKhoanEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITxtMatKhauWindow1 : WinWindow
    {
        
        public UITxtMatKhauWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtMatKhau";
            this.WindowTitles.Add("FrmDangNhap");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtMatKhauEdit
        {
            get
            {
                if ((this.mUITxtMatKhauEdit == null))
                {
                    this.mUITxtMatKhauEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtMatKhauEdit.WindowTitles.Add("FrmDangNhap");
                    #endregion
                }
                return this.mUITxtMatKhauEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtMatKhauEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITableLayoutPanel1Window1 : WinWindow
    {
        
        public UITableLayoutPanel1Window1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "tableLayoutPanel1";
            this.WindowTitles.Add("FrmDangNhap");
            #endregion
        }
        
        #region Properties
        public WinWindow UILoginWindow
        {
            get
            {
                if ((this.mUILoginWindow == null))
                {
                    this.mUILoginWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUILoginWindow.SearchProperties[WinWindow.PropertyNames.Name] = "Login";
                    this.mUILoginWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains));
                    this.mUILoginWindow.WindowTitles.Add("FrmDangNhap");
                    #endregion
                }
                return this.mUILoginWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUILoginWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIFrmChucNangWindow1 : WinWindow
    {
        
        public UIFrmChucNangWindow1()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "FrmChucNang";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.FilterProperties[WinWindow.PropertyNames.OrderOfInvocation] = "2";
            this.WindowTitles.Add("FrmChucNang");
            #endregion
        }
        
        #region Properties
        public UIFrmChucNangClient1 UIFrmChucNangClient
        {
            get
            {
                if ((this.mUIFrmChucNangClient == null))
                {
                    this.mUIFrmChucNangClient = new UIFrmChucNangClient1(this);
                }
                return this.mUIFrmChucNangClient;
            }
        }
        
        public UITxtSoTienWindow1 UITxtSoTienWindow
        {
            get
            {
                if ((this.mUITxtSoTienWindow == null))
                {
                    this.mUITxtSoTienWindow = new UITxtSoTienWindow1(this);
                }
                return this.mUITxtSoTienWindow;
            }
        }
        
        public UIBtnCreditWindow UIBtnCreditWindow
        {
            get
            {
                if ((this.mUIBtnCreditWindow == null))
                {
                    this.mUIBtnCreditWindow = new UIBtnCreditWindow(this);
                }
                return this.mUIBtnCreditWindow;
            }
        }
        
        public UIBtnDebitWindow UIBtnDebitWindow
        {
            get
            {
                if ((this.mUIBtnDebitWindow == null))
                {
                    this.mUIBtnDebitWindow = new UIBtnDebitWindow(this);
                }
                return this.mUIBtnDebitWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIFrmChucNangClient1 mUIFrmChucNangClient;
        
        private UITxtSoTienWindow1 mUITxtSoTienWindow;
        
        private UIBtnCreditWindow mUIBtnCreditWindow;
        
        private UIBtnDebitWindow mUIBtnDebitWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIFrmChucNangClient1 : WinClient
    {
        
        public UIFrmChucNangClient1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "FrmChucNang";
            this.WindowTitles.Add("FrmChucNang");
            #endregion
        }
        
        #region Properties
        public WinWindow UITxtSoTienWindow
        {
            get
            {
                if ((this.mUITxtSoTienWindow == null))
                {
                    this.mUITxtSoTienWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUITxtSoTienWindow.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Số tiền:";
                    this.mUITxtSoTienWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITxtSoTienWindow.WindowTitles.Add("FrmChucNang");
                    #endregion
                }
                return this.mUITxtSoTienWindow;
            }
        }
        
        public WinWindow UILogoutWindow
        {
            get
            {
                if ((this.mUILogoutWindow == null))
                {
                    this.mUILogoutWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUILogoutWindow.SearchProperties[WinWindow.PropertyNames.Name] = "Logout";
                    this.mUILogoutWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains));
                    this.mUILogoutWindow.WindowTitles.Add("FrmChucNang");
                    #endregion
                }
                return this.mUILogoutWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUITxtSoTienWindow;
        
        private WinWindow mUILogoutWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITxtSoTienWindow1 : WinWindow
    {
        
        public UITxtSoTienWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtSoTien";
            this.WindowTitles.Add("FrmChucNang");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtSoTienEdit
        {
            get
            {
                if ((this.mUITxtSoTienEdit == null))
                {
                    this.mUITxtSoTienEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtSoTienEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Số tiền:";
                    this.mUITxtSoTienEdit.WindowTitles.Add("FrmChucNang");
                    #endregion
                }
                return this.mUITxtSoTienEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtSoTienEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIBtnCreditWindow : WinWindow
    {
        
        public UIBtnCreditWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnCredit";
            this.WindowTitles.Add("FrmChucNang");
            #endregion
        }
        
        #region Properties
        public WinButton UIBtnCreditButton
        {
            get
            {
                if ((this.mUIBtnCreditButton == null))
                {
                    this.mUIBtnCreditButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIBtnCreditButton.WindowTitles.Add("FrmChucNang");
                    #endregion
                }
                return this.mUIBtnCreditButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIBtnCreditButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIBtnDebitWindow : WinWindow
    {
        
        public UIBtnDebitWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnDebit";
            this.WindowTitles.Add("FrmChucNang");
            #endregion
        }
        
        #region Properties
        public WinButton UIBtnDebitButton
        {
            get
            {
                if ((this.mUIBtnDebitButton == null))
                {
                    this.mUIBtnDebitButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIBtnDebitButton.WindowTitles.Add("FrmChucNang");
                    #endregion
                }
                return this.mUIBtnDebitButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIBtnDebitButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIFrmDangNhapWindow2 : WinWindow
    {
        
        public UIFrmDangNhapWindow2()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "FrmDangNhap";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.FilterProperties[WinWindow.PropertyNames.OrderOfInvocation] = "3";
            this.WindowTitles.Add("FrmDangNhap");
            #endregion
        }
    }
}
